---
title: "UCSAS Visualization"
author: "Chin-yu"
date: "2023-10-01"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(dbplyr)
library(ggthemes)
library(ggrepel)
library(stargazer)
library(gridExtra)
install.packages('corrplot')
library(corrplot)
tokyo_quad <- read.csv(file = "./original data/data_2017_2021.csv", header = TRUE)
```

# 9/30

```{r}
tokyo_quad %>%
  ggplot()+
  geom_boxplot(mapping = aes(x = Score, y = Apparatus))+
  theme_hc()
```

```{r}
tokyo_quad %>%
  ggplot()+
  geom_boxplot(mapping = aes(x = D_Score, y = Apparatus))+
  theme_hc()

```

```{r}
tokyo_quad %>%
  ggplot()+
  geom_boxplot(mapping = aes(x = E_Score, y = Apparatus))+
  theme_hc()

```

```{r}
champion_round_point <- tokyo_quad %>%
  filter(Round == "qual") %>%
  filter(Rank <= 15)

champion_round_point %>%
  ggplot()+
  geom_boxplot(mapping = aes(x = Score, y = Apparatus))+
  geom_text_repel(data = filter(champion_round_point, Rank == 1), 
                  mapping = aes(x = Score, y = Apparatus, label = LastName),
                  color = "darkred")+
  theme_hc()
```

```{r}
champion_round_point %>%
  ggplot()+
  geom_boxplot(mapping = aes(x = D_Score, y = Apparatus))+
  geom_text_repel(data = filter(champion_round_point, Rank == 1), 
                  mapping = aes(x = D_Score, y = Apparatus, label = LastName),
                  color = "darkred")+
  theme_hc()

```

```{r}
percentiles <- c(quantile(champion_round_point$Rank, 0.01),
                 quantile(champion_round_point$Rank, 0.99))

champion_round_point %>%
  ggplot()+
  geom_boxplot(mapping = aes(x = E_Score, y = Apparatus))+
  geom_text_repel(data = filter(champion_round_point, Rank == 1), 
                  mapping = aes(x = E_Score, y = Apparatus, label = LastName),
                  color = "darkred")+
  theme_hc()

```

# 10/7

```{r}
women <- read.csv(file = "./original data/women_2022_2023.csv", header = TRUE)
women_clean <- women[ , !names(women) %in% c("X")]
all_women <- rbind(tokyo_quad, women_clean)
```

```{r}
by_VT <- all_women %>%
  filter(Apparatus == "VT1" | Apparatus == "VT2" | Apparatus == "VT") 
by_VT <- by_VT %>%
  filter(Score != 0.000)
  
by_FX <- all_women %>%
  filter(Apparatus == "FX")
by_FX <- by_FX %>%
  filter(Score != 0.000)

by_UB <- all_women %>%
  filter(Apparatus == "UB" | Apparatus == "UE")
by_UB <- by_UB %>%
  filter(Score != 0.000)

by_BB <- all_women %>%
  filter(Apparatus == "BB")
by_BB <- by_BB %>%
  filter(Score != 0.000)

```

## Graph

```{r}
by_VT %>%
  ggplot()+
  geom_point(mapping = aes(x = Rank, y = D_Score))+
  geom_smooth(mapping = aes(x = Rank, y = D_Score), method = lm)+
  theme_minimal()

```

```{r}
by_VT %>%
  ggplot()+
  geom_point(mapping = aes(x = Rank, y = E_Score))+
  geom_smooth(mapping = aes(x = Rank, y = E_Score), method = lm)+
  theme_minimal()
```

```{r}
by_BB %>%
  ggplot()+
  geom_point(mapping = aes(x = Rank, y = D_Score))+
  geom_smooth(mapping = aes(x = Rank, y = D_Score), method = lm)+
  theme_minimal()
```

```{r}
by_BB %>%
  ggplot()+
  geom_point(mapping = aes(x = Rank, y = E_Score))+
  geom_smooth(mapping = aes(x = Rank, y = E_Score), method = lm)+
  theme_minimal()
```

```{r}
by_FX %>%
  ggplot()+
  geom_point(mapping = aes(x = Rank, y = D_Score))+
  geom_smooth(mapping = aes(x = Rank, y = D_Score), method = lm)+
  theme_minimal()
```

```{r}
by_FX %>%
  ggplot()+
  geom_point(mapping = aes(x = Rank, y = E_Score))+
  geom_smooth(mapping = aes(x = Rank, y = E_Score), method = lm)+
  theme_minimal()
```

```{r}
by_UB %>%
  ggplot()+
  geom_point(mapping = aes(x = Rank, y = D_Score))+
  geom_smooth(mapping = aes(x = Rank, y = D_Score), method = lm)+
  theme_minimal()
```

```{r}
by_BB %>%
  ggplot()+
  geom_point(mapping = aes(x = Rank, y = E_Score))+
  geom_smooth(mapping = aes(x = Rank, y = E_Score), method = lm)+
  theme_minimal()
```

## Regression

```{r}
regression_VT_D_Score <- lm(D_Score ~ Rank, data = by_VT)
summary(regression_VT_D_Score)
```

```{r}
regression_VT_E_Score <- lm(E_Score ~ Rank, data = by_VT)
summary(regression_VT_E_Score)
```

```{r}
regression_BB_D_Score <- lm(D_Score ~ Rank, data = by_BB)
summary(regression_BB_D_Score)
```

```{r}
regression_BB_E_Score <- lm(E_Score ~ Rank, data = by_BB)
summary(regression_BB_E_Score)
```

```{r}
regression_FX_D_Score <- lm(D_Score ~ Rank, data = by_FX)
summary(regression_FX_D_Score)
```

```{r}
regression_FX_E_Score <- lm(E_Score ~ Rank, data = by_FX)
summary(regression_FX_E_Score)
```

```{r}
regression_UB_D_Score <- lm(D_Score ~ Rank, data = by_UB)
summary(regression_UB_D_Score)
```

```{r}
regression_UB_E_Score <- lm(E_Score ~ Rank, data = by_UB)
summary(regression_UB_E_Score)
```

## After filter

```{r}
by_VT_Olympics_qualification <- by_VT %>%
  filter(Round == "qual" & Competition == "Olympic Games")

regression_VT_D_Score_olympics <- lm(D_Score ~ Rank, data = by_VT_Olympics_qualification)
stargazer(regression_VT_D_Score_olympics, type = "text")
```

```{r}
regression_VT_E_Score_olympics <- lm(E_Score ~ Rank, data = by_VT_Olympics_qualification)
stargazer(regression_VT_E_Score_olympics, type = "text")
```

```{r}
by_BB_Olympics_qualification <- by_BB %>%
  filter(Round == "qual" & Competition == "Olympic Games")

regression_BB_D_Score_olympics <- lm(D_Score ~ Rank, data = by_BB_Olympics_qualification)
stargazer(regression_BB_D_Score_olympics, type = "text")
```

```{r}
regression_BB_E_Score_olympics <- lm(E_Score ~ Rank, data = by_BB_Olympics_qualification)
stargazer(regression_BB_E_Score_olympics, type = "text")
```

```{r}
by_FX_Olympics_qualification <- by_FX %>%
  filter(Round == "qual" & Competition == "Olympic Games")

regression_FX_D_Score_olympics <- lm(D_Score ~ Rank, data = by_FX_Olympics_qualification)
stargazer(regression_FX_D_Score_olympics, type = "text")
```

```{r}
regression_FX_E_Score_olympics <- lm(E_Score ~ Rank, data = by_FX_Olympics_qualification)
stargazer(regression_FX_E_Score_olympics, type = "text")
```

```{r}
by_UB_Olympics_qualification <- by_UB %>%
  filter(Round == "qual" & Competition == "Olympic Games")

regression_UB_D_Score_olympics <- lm(D_Score ~ Rank, data = by_UB_Olympics_qualification)
stargazer(regression_UB_D_Score_olympics, type = "text")
```

```{r}
regression_UB_E_Score_olympics <- lm(Rank ~ E_Score , data = by_UB_Olympics_qualification)
stargazer(regression_UB_E_Score_olympics, type = "text")
```

```{r}
gd <- tokyo_quad %>%
  filter(Round == 'qual' & Competition == "Olympic Games")
gdShort <- gd[9:14]
forcorrplot <- cor(gdShort)
corrplot(forcorrplot)
cor(gdShort)
```
